## Assignment 1 - 20MIS0091 A.P.Swathi Lakshmi

#### Q1. Assign your Name to variable name and Age to variable age. Make a python program that prints your name and age.

In [2]:
name='A.P.Swathi Lakshmi'
age=19
print('My name is: ',name)
print('My age is: ',age)

My name is:  A.P.Swathi Lakshmi
My age is:  19


#### Q2. X="Datascience is used to extract meaningful insights."  - Split the string.

In [6]:
X='Datascience is used to extract meaningful insights'
splitted_str=X.split()
print(splitted_str)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights']


#### Q3. Make a function that gives multiplication of two numbers.

In [13]:
def multiplication(a,b):
    mul=a*b;
    print('Multiplication of a anb b is:', mul)
a=int(input('Enter a: '))
b=int(input('Enter b: '))
multiplication(a,b)

Enter a: 22
Enter b: 10
Multiplication of a anb b is: 220


#### Q4. Create a Dictionary of 5 states with their capitals. Also print the keys and values.

In [30]:
dict1={'Andhra Pradesh': 'Amaravati','Tamil Nadu': 'Chennai','Kerala': 'Thiruvathanapuram','Karnataka': 'Bengaluru','Maharashtra': 'Mumbai'}
print('The dictionary items are:', '\n', dict1.items(), '\n')
print('The keys are:', dict1.keys(), '\n')
print('The values are: ', dict1.values(), '\n')

The dictionary items are: 
 dict_items([('Andhra Pradesh', 'Amaravati'), ('Tamil Nadu', 'Chennai'), ('Kerala', 'Thiruvathanapuram'), ('Karnataka', 'Bengaluru'), ('Maharashtra', 'Mumbai')]) 

The keys are: dict_keys(['Andhra Pradesh', 'Tamil Nadu', 'Kerala', 'Karnataka', 'Maharashtra']) 

The values are:  dict_values(['Amaravati', 'Chennai', 'Thiruvathanapuram', 'Bengaluru', 'Mumbai']) 



#### Q5. Create a list of 1000 numbers using range function.

In [ ]:
import numpy as np

In [36]:
list=np.arange(1,1001)
print('The list containing numbers is: ')
print(list)

The list containing numbers is: 
[   1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20   21   22   23   24   25   26   27   28
   29   30   31   32   33   34   35   36   37   38   39   40   41   42
   43   44   45   46   47   48   49   50   51   52   53   54   55   56
   57   58   59   60   61   62   63   64   65   66   67   68   69   70
   71   72   73   74   75   76   77   78   79   80   81   82   83   84
   85   86   87   88   89   90   91   92   93   94   95   96   97   98
   99  100  101  102  103  104  105  106  107  108  109  110  111  112
  113  114  115  116  117  118  119  120  121  122  123  124  125  126
  127  128  129  130  131  132  133  134  135  136  137  138  139  140
  141  142  143  144  145  146  147  148  149  150  151  152  153  154
  155  156  157  158  159  160  161  162  163  164  165  166  167  168
  169  170  171  172  173  174  175  176  177  178  179  180  181  182
  183  184  185  186  187  188  189  190  19

#### Q6. Create an identity matrix of dimension 4 by 4.

In [38]:
print('The 4 X 4 Identity matrix is: ')
print(np.eye(4))

The 4 X 4 Identity matrix is: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### Q7. Create a 3x3 matrix with values ranging from 1 to 9.

In [41]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
matrix=np.array(my_matrix)
print('The matrix is: ') 
print(matrix)

The matrix is: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Q8. Create 2 similar dimensional array and perform sum on them.

In [46]:
arr1=np.array([[10,12,14],[22,24,26],[8,18,28]])
print('Array 1 is:', '\n', arr1)
arr2=np.array([[11,22,33],[15,30,45],[5,10,15]])
print('Array 2 is: ', '\n', arr2)
sum=arr1+arr2
print('The sum of the two arrays is: ', '\n', sum)

Array 1 is: 
 [[10 12 14]
 [22 24 26]
 [ 8 18 28]]
Array 2 is:  
 [[11 22 33]
 [15 30 45]
 [ 5 10 15]]
The sum of the two arrays is:  
 [[21 34 47]
 [37 54 71]
 [13 28 43]]


#### Q9. Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive).

In [49]:
import pandas as pd

In [52]:
dates=pd.date_range(start='02/01/2023', end='03/01/2023')
print('The series of dates are: ', '\n', dates)

The series of dates are:  
 DatetimeIndex(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
               '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
               '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28',
               '2023-03-01'],
              dtype='datetime64[ns]', freq='D')


#### Q10. Given a dictionary, convert it into corresponding dataframe and display it.
#### dictionary= {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales' : [250, 200, 240])

In [58]:
dictionary={'Brand': ['Maruti','Renault','Hyundai'], 'Sales': [250,200,240]}
dict_df=pd.DataFrame(dictionary)
print('DataFrame is: ', '\n', dict_df)

DataFrame is:  
      Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
