In [ ]:
#1
name="K.Gnana Varshita"
age="20"
print(name)
print(age)

K.Gnana Varshita
20


In [ ]:
#2
X="Datascience is used to extract meaningful insights"
s_split=X.split()
print(s_split)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights']


In [ ]:
#3
def mul(a,b):
  c=a*b
  return c

mul(5,5)



25

In [ ]:
#4
s_c={
    "Andhra Pradesh":"Amaravati",
     "Telanga":"Hyderabad",
     "Tamil Nadu":"Chennai",
     "Karnataka":"Bengaluru",
}

for s in s_c.keys():
  print(s)

print("*********")

for c in s_c.values():
  print(c)



Andhra Pradesh
Telanga
Tamil Nadu
Karnataka
*********
Amaravati
Hyderabad
Chennai
Bengaluru


In [ ]:
#5
nums= list(range(1,1001))
print(nums[:1000])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

In [ ]:
#6
import numpy as np
I_matrix=np.eye(4)
print(I_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#7
matrix=np.arange(1,10).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#8
a1 =np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([[10,11,12],[13,14,15],[16,17,18]])

result =a1+a2
print(result)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [ ]:
#9
import datetime
s_date=datetime.date(2023,4,8)
e_date=datetime.date(2023,5,8)
date_range=np.arange(s_date,e_date+datetime.timedelta(days=1),dtype='datetime64[D]')
for date in date_range:
  print(date)

2023-04-08
2023-04-09
2023-04-10
2023-04-11
2023-04-12
2023-04-13
2023-04-14
2023-04-15
2023-04-16
2023-04-17
2023-04-18
2023-04-19
2023-04-20
2023-04-21
2023-04-22
2023-04-23
2023-04-24
2023-04-25
2023-04-26
2023-04-27
2023-04-28
2023-04-29
2023-04-30
2023-05-01
2023-05-02
2023-05-03
2023-05-04
2023-05-05
2023-05-06
2023-05-07
2023-05-08


In [ ]:
#10
import pandas as pd
dictionary={'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
df =pd.DataFrame(dictionary)
print(df)

     Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240
